### PR TITLE
Parsing published ISO STS XML document (ISO 8601-1)

### LINKED ISSUE #5: Fully parse published ISO STS XML document (ISO 8601-1)
https://github.com/metanorma/iso-8601-1/blob/dfdff8e439ae77b5d1e7a3f9c7bc51c9a61d92f3/submission/iso-8601-1-nisosts/C070907e.xml

We want to round-trip this document.

### PR DESCRIPTION
**Pull request by HassanAkbar**
Fully parsing published ISO STS XML document (ISO 8601-1) -> https://github.com/metanorma/iso-8601-1/blob/dfdff8e439ae77b5d1e7a3f9c7bc51c9a61d92f3/submission/iso-8601-1-nisosts/C070907e.xml

closes #5

### CODE REVIEW

**Comment by ronaldtse** [comment]
@HassanAkbar this file is private and we can't use it as spec. Let me see if I can find out a testable sample, e.g. ISO Rice.

**Comment by ronaldtse** [comment]
@HassanAkbar can we first remove (i.e. scrub away the private content) and then merge the PR? We will need to replace the test file anyway.

**Comment by HassanAkbar** [comment]
@ronaldtse Sure, I'll update this PR.

**Review by ronaldtse — APPROVED** [review]
Thanks @HassanAkbar ! We should find a way to test these...

**Pull request merged**
